version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: weather-sensor-db
    environment:
      POSTGRES_DB: weather_sensor
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather_user -d weather_sensor"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: weather-sensor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@weathersensor.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - weather-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  weather-network:
    driver: bridge