spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_sensor
    username: weather_user
    password: weather_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

logging:
  level:
    com.weathersensor.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG